// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrWoLiFME9h3r0y5CqWU94rSj00w08A1M',
    appId: '1:582208935844:web:be96f6071aac76c1619331',
    messagingSenderId: '582208935844',
    projectId: 'volunteer-tutor',
    authDomain: 'volunteer-tutor.firebaseapp.com',
    storageBucket: 'volunteer-tutor.appspot.com',
    measurementId: 'G-2KMK2668T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8kp4VRyUTgRSTP8E-hIUVG0bI8pROJgY',
    appId: '1:582208935844:android:181adf120a5a0c28619331',
    messagingSenderId: '582208935844',
    projectId: 'volunteer-tutor',
    storageBucket: 'volunteer-tutor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtatV-HhB1pTq81wNT1ZJfi6xtEUNE4YY',
    appId: '1:582208935844:ios:a019ffcb7f8866b7619331',
    messagingSenderId: '582208935844',
    projectId: 'volunteer-tutor',
    storageBucket: 'volunteer-tutor.appspot.com',
    iosClientId: '582208935844-egdbdjalq17vn8gr7tj54rkameh9cfsv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtatV-HhB1pTq81wNT1ZJfi6xtEUNE4YY',
    appId: '1:582208935844:ios:a019ffcb7f8866b7619331',
    messagingSenderId: '582208935844',
    projectId: 'volunteer-tutor',
    storageBucket: 'volunteer-tutor.appspot.com',
    iosClientId: '582208935844-egdbdjalq17vn8gr7tj54rkameh9cfsv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorApp',
  );
}
